from . import product_product
from . import reception
from . import reception_details
from . import reception_detail_provisional
from . import fishing_config
from . import stock_pallet
from . import fish_service_stock
from . import account_move
from . import charges
from . import maintenance_equipment
from . import res_company
